name: 'README Check'
description: 'Validates README format'
author: 'Garret Patten'

# TODO: Add branding

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  readmePath:
    description: 'The README path'
    required: true
    default: 'README.md'

outputs:
  timestamp:
    description: 'README check timestamp'

runs:
  using: 'node12'
  main: 'dist/index.js'