name: 'Example Workflow'

on:
    pull_request:
        branches: [ main ]
    push:
        branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check README
        id: readmeCheck
        uses: garretpatten/readme-check@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the output time
        run: |
          echo "README check has completed"
          echo "Timestamp: ${{ steps.readmeCheck.outputs.timestamp }}"