name: 'readme-check Workflow'

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check README
        id: readmeCheckId
        uses: garretpatten/readme-check@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the output time
        run: |
          echo "README check has completed"
          echo "Timestamp: ${{ steps.readmeCheckId.outputs.time }}"